---

- hosts: web

  tasks:
  - name: recreate container
    docker_container:
      name: antlrpad
      pull: true
      image: aleksys/antlrpad
      command: "-J-Xmx64m -Dplay.crypto.secret=e9a7825e-4144-11e6-9475-f45c89b0e36f -Dplay.evolutions.db.default.autoApply=true"
      state: started
      recreate: yes
      api_version: 1.19
      ports:
        - "9000:9000"
